### ISSUE TITLE
[event-driven-services.adoc] Payment Status never proceeds to COMPLETED/FAILED

### ISSUE THREAD

**Issue by nobusue** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-guides#33] opened 2022-03-23 15:59 UTC
### Problem
Order service stops consuming from topic "Payments" due to NPE in KafkaOrders. It keeps "Payment Status=PROCESSING" at Orders page forever.

### Root Cause
KafkaOrders requires "status" field in incoming JSON message. If not, it causes NPE.
```
2022-03-23 10:39:39,234 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-1) SRMSG00200: The method com.redhat.cloudnative.KafkaOrders#onMessagePayments has thrown an exception: java.lang.NullPointerException
	at com.redhat.cloudnative.KafkaOrders.onMessagePayments(KafkaOrders.java:50)
```
This is caused by test message we sent in previous step. (Using curl command)

### Workaround
Restart Order service.

**Comment by danieloh30** [comment] 2022-03-23 17:47
did this error happen right after you deployed the order service with "KafkaOrders.java"? If this issue was fixed when you just restarted the order pod, I doubt the deployment was done properly to connect to the Kafka topic. I just tried to go through m4 from scratch then it works for me well. I can't produce this issue.

Can you reproduce this issue when you start over m4 or even after deploying the order service again?

**Comment by ssetoredhat** [comment] 2022-03-24 06:33
I was the first to find this problem.
nobusue was also able to find it, too.

It looks like the content of the test message is not registered in the DB and is causing the error.
Probably newOrder.status is cause of NPE.

The raw log and source(KafkaOrders.java) are here.
https://gist.github.com/ssetoredhat/fcebb06df468a5312ad2e0d8711a0e36

**Comment by danieloh30** [comment] 2022-03-24 12:35
Can I access your cluster to reproduce this? I can't reproduce in my 2 clusters. Also, did you have this issue when you ran the curl command with the dummy data or testing via GUI too?

**Comment by ssetoredhat** [comment] 2022-03-25 07:33
I'm sorry. I am new to kafka so I don't know. And my cluster is destroyed...

**Comment by danieloh30** [comment] 2022-03-25 11:30
No worries. I would close this issue at this moment since I can't reproduce it in the workshop environment. Instead, I'll put this on the backlogs.

**Closed as completed by danieloh30** 2022-03-25 11:30 UTC
